In [50]:
import pandas as pd
import numpy as np
import re
import xlsxwriter

In [51]:
ce1 = pd.read_excel(r'H:\6.-Universidad Arturo Prat - Python\Evaluación Docente 2022\Estudiantes\CE_1erSemestre.xlsx')
ce2 = pd.read_excel(r'H:\6.-Universidad Arturo Prat - Python\Evaluación Docente 2022\Estudiantes\CE_2dorSemestre.xlsx')
ptu1 = pd.read_excel(r'H:\6.-Universidad Arturo Prat - Python\Evaluación Docente 2022\Estudiantes\PTU_1erSemestre.xlsx')
ptu2 = pd.read_excel(r'H:\6.-Universidad Arturo Prat - Python\Evaluación Docente 2022\Estudiantes\PTU_2doSemestre.xlsx')
tns1 = pd.read_excel(r'H:\6.-Universidad Arturo Prat - Python\Evaluación Docente 2022\Estudiantes\TNS_1erSemestre.xlsx')
tns2 = pd.read_excel(r'H:\6.-Universidad Arturo Prat - Python\Evaluación Docente 2022\Estudiantes\TNS_2doSemestre.xlsx')

In [52]:
# Función de limpieza de datos

def clean_estudiantes(data):
    data = data.iloc[7:]
    data = data.iloc[:, 1:]
    data = data.reset_index(drop=True)
    data.columns = data.iloc[0]
    data = data.iloc[1:]
    data = data.rename(columns=lambda x: re.sub(r'\W+', '_', x.strip().lower()))
    return data

In [53]:
ce1 = clean_estudiantes(ce1)
ce2 = clean_estudiantes(ce2)
ptu1 = clean_estudiantes(ptu1)
ptu2 = clean_estudiantes(ptu2)
tns1 = clean_estudiantes(tns1)
tns2 = clean_estudiantes(tns2)

In [54]:
Estudiantes2022 = pd.concat([ce1,ce2,ptu1,ptu2,tns1,tns2])

In [55]:
Estudiantes2022

,sexo,proceso,semestre,sede,tipo_carrera,unidad_academica,codigo_carrera,nombre_carrera,codigo_actividad,nombre_actividad,...,respuesta_1_8,respuesta_1_9,respuesta_1_10,respuesta_1_11,respuesta_1_12,respuesta_1_13,respuesta_2_1,respuesta_2_2,edad_docente,contrato_docente
1,Mujer,2022,1,Iquique,Pregrado Trabajador,Facultad De Ciencias Empresariales,3781,Ingeniería De Ejecución En Administración De E...,EAE34,Comercializacion I,...,--,--,--,--,--,--,--,--,NaN,NaN
2,Mujer,2022,1,Iquique,Pregrado Trabajador,Facultad De Ciencias Empresariales,3781,Ingeniería De Ejecución En Administración De E...,EAE34,Comercializacion I,...,--,--,--,--,--,--,--,--,NaN,NaN
3,Mujer,2022,1,Iquique,Pregrado Trabajador,Facultad De Ciencias Empresariales,3781,Ingeniería De Ejecución En Administración De E...,EAE34,Comercializacion I,...,--,--,--,--,--,--,--,--,NaN,NaN
4,Mujer,2022,1,Iquique,Pregrado Trabajador,Facultad De Ciencias Empresariales,3781,Ingeniería De Ejecución En Administración De E...,EAE34,Comercializacion I,...,--,--,--,--,--,--,--,--,NaN,NaN
5,Hombre,2022,1,Iquique,Pregrado Trabajador,Facultad De Ciencias Empresariales,3781,Ingeniería De Ejecución En Administración De E...,EAE34,Comercializacion I,...,--,--,--,--,--,--,--,--,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26108,Hombre,2022,2,Arica,Técnicas,Formación Técnica,2561,Técnico De Nivel Superior Agrícola,TNA41,Técnicas Y Manejo De Post Cosecha,...,--,--,--,--,--,--,--,--,34,Honorario
26109,Hombre,2022,2,Arica,Técnicas,Formación Técnica,2561,Técnico De Nivel Superior Agrícola,TNA41,Técnicas Y Manejo De Post Cosecha,...,--,--,--,--,--,--,--,--,34,Honorario
26110,Mujer,2022,2,Arica,Técnicas,Formación Técnica,2561,Técnico De Nivel Superior Agrícola,TNA41,Técnicas Y Manejo De Post Cosecha,...,--,--,--,--,--,--,--,--,34,Honorario
26111,Hombre,2022,2,Arica,Técnicas,Formación Técnica,2561,Técnico De Nivel Superior Agrícola,TNA21,Biología Agrícola,...,--,--,--,--,--,--,--,--,27,Honorario
26112,Hombre,2022,2,Arica,Técnicas,Formación Técnica,2561,Técnico De Nivel Superior Agrícola,TNA23,Tecnología De Riego,...,--,--,--,--,--,--,--,--,27,Honorario

In [56]:
drop_columnas = ['sexo','edad_docente','contrato_docente']

In [57]:
Estudiantes2022 = Estudiantes2022.drop(drop_columnas,axis=1)

Empieza el procedimiento de calcular el nivel de parcitipación

In [58]:
CoberturaEstudiantes2022 = Estudiantes2022.groupby(['proceso','semestre','sede','tipo_carrera','unidad_academica','codigo_carrera','nombre_carrera','codigo_actividad','nombre_actividad',
                         'paralelo','tipo_asig','rut_docente','nombre_docente','apaterno_docente','amaterno_docente','estado']).size().reset_index(name='count')

In [59]:
CoberturaEstudiantes2022 = CoberturaEstudiantes2022.pivot_table(index=['proceso', 'semestre', 'sede', 'tipo_carrera', 'unidad_academica', 'codigo_carrera', 'nombre_carrera', 'codigo_actividad', 'nombre_actividad', 'paralelo',
                                                                        'tipo_asig', 'rut_docente', 'nombre_docente', 'apaterno_docente', 'amaterno_docente'], columns='estado', values='count', fill_value=0).reset_index()

In [60]:
CoberturaEstudiantes2022 = CoberturaEstudiantes2022.rename(columns=lambda x: re.sub(r'\W+', '_', x.strip().lower()))

In [61]:
CoberturaEstudiantes2022['total'] = CoberturaEstudiantes2022['no_iniciada'] + CoberturaEstudiantes2022['finalizado'] + CoberturaEstudiantes2022['pendiente']

In [62]:
CoberturaEstudiantes2022['partipacion']= round((CoberturaEstudiantes2022['finalizado'] / CoberturaEstudiantes2022['total']) * 100,2)

In [ ]:
CoberturaEstudiantes2022

Ahora inicia el proceso de Calcular los resultados

In [ ]:
Columnas_respuesta = [col for col in Estudiantes2022.columns if col.startswith('respuesta')]
Escala_Puntuacion = {'Siempre': 3.0, 'Generalmente': 2.0, 'Pocas veces': 1.0, 'Nunca': 0.0, '--': 0.0}

In [ ]:
Estudiantes2022[Columnas_respuesta] = Estudiantes2022[Columnas_respuesta].replace(Escala_Puntuacion)

In [ ]:
Estudiantes2022

In [ ]:
# Definir las columnas a excluir
columnas_excluidas = ['inicio_aplicacion', 'fin_aplicacion', 'estado', 'fecha_inicio', 'fecha_fin']

# Realizar la agrupación y cálculo del promedio
grupos = Estudiantes2022.groupby(['proceso', 'semestre', 'sede', 'tipo_carrera', 'unidad_academica', 'codigo_carrera', 'nombre_carrera', 'codigo_actividad', 'nombre_actividad',
                                  'paralelo', 'tipo_asig', 'rut_docente', 'nombre_docente', 'apaterno_docente', 'amaterno_docente'])

promedio = grupos.agg(lambda x: round(x.mean(), 2) if x.name.startswith('respuesta') else x)

# Crear un nuevo DataFrame excluyendo las columnas indicadas
ResultadosEstudiantes2022 = promedio.drop(columns=columnas_excluidas)

In [ ]:
EvaluacionEstudiantes2022 = CoberturaEstudiantes2022.merge(ResultadosEstudiantes2022, on=['proceso', 'semestre', 'sede', 'tipo_carrera', 'unidad_academica', 'codigo_carrera', 'nombre_carrera', 'codigo_actividad',
                                                                      'nombre_actividad', 'paralelo', 'tipo_asig', 'rut_docente', 'nombre_docente', 'apaterno_docente', 'amaterno_docente'])

In [ ]:
EvaluacionEstudiantes2022 = EvaluacionEstudiantes2022.groupby(['proceso', 'semestre', 'sede', 'tipo_carrera', 'unidad_academica', 'codigo_carrera', 'nombre_carrera', 'codigo_actividad', 'nombre_actividad',
                                  'paralelo', 'tipo_asig', 'rut_docente', 'nombre_docente', 'apaterno_docente', 'amaterno_docente'])

In [ ]:
columnas_mediador = EvaluacionEstudiantes2022.columns[EvaluacionEstudiantes2022.columns.str.startswith('respuesta_1_')]

AttributeError: 'DataFrameGroupBy' object has no attribute 'columns'

In [ ]:
EvaluacionEstudiantes2022['mediador'] = EvaluacionEstudiantes2022[columnas_mediador].mean(axis=1)

In [ ]:
EvaluacionEstudiantes2022

,proceso,semestre,sede,tipo_carrera,unidad_academica,codigo_carrera,nombre_carrera,codigo_actividad,nombre_actividad,paralelo,...,respuesta_1_8,respuesta_1_9,respuesta_1_10,respuesta_1_11,respuesta_1_12,respuesta_1_13,respuesta_2_1,respuesta_2_2,total_mediador,mediador
0,2022,1,Antofagasta,Pregrado Trabajador,Facultad De Ciencias Empresariales,3710,Ingeniería De Ejecución En Control De Gestión,ICG71,Finanzas Ii,FA,...,0.45,0.41,0.45,0.55,0.50,0.45,0.50,0.55,NaN,0.496923
1,2022,1,Antofagasta,Pregrado Trabajador,Facultad De Ciencias Empresariales,3710,Ingeniería De Ejecución En Control De Gestión,ICG72,Comercio Internacional,FA,...,1.38,1.52,1.45,1.45,1.55,1.55,1.48,1.55,NaN,1.468462
2,2022,1,Antofagasta,Pregrado Trabajador,Facultad De Ciencias Empresariales,3710,Ingeniería De Ejecución En Control De Gestión,ICG73,S.I.A. I,FA,...,0.36,0.36,0.36,0.41,0.41,0.41,0.41,0.41,NaN,0.383077
3,2022,1,Antofagasta,Pregrado Trabajador,Facultad De Ciencias Empresariales,3710,Ingeniería De Ejecución En Control De Gestión,ICG76,Técnicas De Auditoría Y De Control,FA,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.000000
4,2022,1,Antofagasta,Pregrado Trabajador,Facultad De Ciencias Empresariales,3710,Ingeniería De Ejecución En Control De Gestión,ICG77,Adiestramiento Computacional Profesional,FA,...,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,NaN,0.140000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4877,2022,2,Victoria,Técnicas,Formación Técnica,2560,Técnico De Nivel Superior Asistente En Educaci...,TEP43,Didácticas Niveles Medios,AAA,...,1.33,1.33,1.31,1.33,1.33,1.33,1.33,1.33,NaN,1.325385
4878,2022,2,Victoria,Técnicas,Formación Técnica,2560,Técnico De Nivel Superior Asistente En Educaci...,TEP44,Expresión Artísticas Ii,LM,...,1.03,1.06,1.06,1.12,1.12,1.12,1.18,1.12,NaN,1.073846
4879,2022,2,Victoria,Técnicas,Formación Técnica,2560,Técnico De Nivel Superior Asistente En Educaci...,TEP45,Salud Y Bienestar Ii,DV7,...,1.34,1.41,1.38,1.41,1.41,1.41,1.34,1.38,NaN,1.366154
4880,2022,2,Victoria,Técnicas,Formación Técnica,2560,Técnico De Nivel Superior Asistente En Educaci...,TNT20,Inglés Técnico,DV3,...,0.55,0.55,0.55,0.48,0.45,0.48,0.52,0.55,NaN,0.526923
4881,2022,2,Victoria,Técnicas,Formación Técnica,2560,Técnico De Nivel Superior Asistente En Educaci...,TNT21,Herramientas Informáticas,DV2,...,0.47,0.50,0.47,0.47,0.47,0.47,0.50,0.50,NaN,0.476923

In [ ]:
writer = pd.ExcelWriter('Estudiantes2022.xlsx', engine='xlsxwriter')
EvaluacionEstudiantes2022.to_excel(writer, sheet_name='Estudiantes2022', index=True)
writer.save()

C:\Users\aigna\AppData\Local\Temp\ipykernel_8916\2547914818.py:3: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()